name: pyfinance
channels:
  - defaults
dependencies:
  - matplotlib
  - numpy
  - scipy
  - statsmodels
  - pandas
  - python
  - pytorch
  - tensorflow
  - keras
  - SciKit-Learn
  - pip 
  - pip:
      - zipline
      - pyfolio
      - alphalens
      - empyrical
      - quandl
      - numexpr
      - pymc3
      - gs-quant
      - qfrm
      - QuantLib-Python
      - qiskit
      - quantecon
 
