name: pyfinance
channels:
  - defaults
dependencies:
  - matplotlib
  - numpy
  - statsmodel
  - openssl
  - pandas
  - pandas-datareader
  - patsy
  - pyparsing
  - pyqt
  - python
  - python-dateutil
  - pytz
  - qt
  - requests
  - setuptools
  - sip
  - six
  - pip 
  - pip:
      - certifi
      - chardet
      - idna
      - inflection
      - more-itertools
      - quandl
      - urllib3
      - zipline
      - pyfolio
      - alphalens
      - quantdsl
      - pymc3
      - TA-Lib
      - pyfin
      - vollib
      - QuantPy
      - ffn
      - pynance
      - trade
      - finance
      - gs-quant
      - financepy
      - analyzer
      - pandas_ta
      - empyrical
      - qfrm
      - trading-calendars
      - pandas_market_calendars
      - QuantLib-Python
      - findatapy
      - googlefinance
      - yahoo-finance
      - yfinanceapi
      - pyhoofinance
      - pandas-finance
      - wallstreet
      - chinesestockapi
      - cn_stock_src
      - ccy
      - coinmarketcap
      - investpy
      - yliveticke
      - sympy
      - xlwings
      - qiskit
      - pytorch
      - tensorflow
      - keras
      - SciKit-Learn
      - quantecon
      - interpolation
      - sphinxcontrib-jupyter
      - sphinxcontrib-bibtex==1.0
      - joblib
