name: pyfinance
channels:
  - defaults
dependencies:
  - matplotlib
  - numpy
  - scipy
  - statsmodels
  - pandas
  - pandas-datareader
  - openssl
  - patsy
  - pyparsing
  - pyqt
  - python
  - python-dateutil
  - pytz
  - qt
  - requests
  - setuptools
  - sip
  - six
  - pip 
  - pip:
      - quandl
      - numexpr
      - zipline
      - pyfolio
      - alphalens
      - quantdsl
      - pymc3
      - TA-Lib
      - pyfin
      - QuantPy
      - pynance
      - gs-quant
      - empyrical
      - qfrm
      - QuantLib-Python
      - qiskit
      - pytorch
      - tensorflow
      - keras
      - SciKit-Learn
      - quantecon
 
