name: pyfinance
channels:
  - defaults
dependencies:
  - matplotlib
  - numpy
  - scipy
  - statsmodels
  - pandas
  - python
  - pip 
  - pip:
      - quandl
      - QuantLib-Python
      - quantecon
