name: pyfinance
channels:
  - defaults
dependencies:
  - matplotlib
  - numpy
  - scipy
  - statsmodels
  - pandas
  - python
  - quandl
  - quantecon
  - tensorflow
  - scikit-learn
  - pip:
    - quantlib-python
    - qiskit
