name: pyfinance
channels:
  - defaults
dependencies:
  - matplotlib
  - numpy
  - scipy
  - statsmodels
  - pandas
  - python
  - pytorch
  - tensorflow
  - keras
  - SciKit-Learn
  - pip 
  - pip:
      - quandl
      - zipline
      - pyfolio
      - alphalens
      - QuantLib-Python
      - quantecon
      - qiskit 
